#!/bin/bash

source <(curl -sS https://raw.githubusercontent.com/TheGuild-ops/LJ/main/tool/dependencies.sh)
source <(curl -sS https://raw.githubusercontent.com/TheGuild-ops/LJ/main/tool/fetch_or_ask)

dependencies=("docker-ce" "docker-ce-cli" "containerd.io" "docker-buildx-plugin" "docker-compose-plugin" "npm")

readonly PNAME=elixir
readonly WALLET_PROVIDER=metamask
readonly NETWORK=sepolia
target_directory="/root/node/${PNAME}"
mkdir -p $target_directory
cd $target_directory

wget https://files.elixir.finance/Dockerfile -O Dockerfile
bash <(curl -sS https://raw.githubusercontent.com/TheGuild-ops/LJ/main/tool/ethGen)

WALLET=$(fetch_or_ask $WALLET_PROVIDER $PNAME WALLET)
WALLET_SEED=$(fetch_or_ask $WALLET_PROVIDER $PNAME WALLET_SEED)
STATUS=$(fetch_or_ask $PNAME STATUS)
NODENAME=$(fetch_or_ask NODENAME)

sed -i "s/ENV ADDRESS=0x.*/ENV ADDRESS=$WALLET/" "Dockerfile"
sed -i "s/ENV PRIVATE_KEY=0x.*/ENV PRIVATE_KEY=0x$WALLET_SEED/" "Dockerfile"
sed -i "s/ENV VALIDATOR_NAME=.*/ENV VALIDATOR_NAME=$NODENAME/" "Dockerfile"

docker kill ev
docker rm ev
docker pull elixirprotocol/validator:testnet-2
docker build . -f Dockerfile -t elixir-validator