#!/bin/bash

# Функция для проверки наличия и установки go-ethereum

  if ! command -v geth &> /dev/null; then
    echo "Ethereum не установлен. Установка..."
    sudo apt-get update
    sudo apt-get install -y software-properties-common
    sudo add-apt-repository -y ppa:ethereum/ethereum
    sudo apt-get update
    sudo apt-get install -y ethereum
  else
    echo "Ethereum уже установлен"
  fi
