#!/bin/bash

# Проверяем, установлен ли subkey
source /root/.profile
if ! command -v subkey &> /dev/null; then
    echo "subkey is not installed. Installing..."
    cargo +nightly install --force subkey
    cd 
    git clone https://github.com/paritytech/substrate.git
    cd substrate
    cargo +nightly build --package subkey --release
    sudo mv target/release/subkey /usr/local/bin/ || exit
else
    echo "subkey is already installed."
fi

subkey generate >> $HOME/key.txt

# Выводим сгенерированный ключ
echo "-----------------------------------------------------------------------------------------------"
cat $HOME/key.txt
